CriminologyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Criminology_App.urls')),
    path('summernote/', include('django_summernote.urls')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Criminology_App/urls.py
from django.conf.urls import url
from django.urls import path
from Criminology_App import views

app_name = 'Criminology_App'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('event/', views.events, name='event'),
    path('event_details/<int:pk>/', views.event_details, name='event_details'),
    path('research_publication/', views.research_publication, name='research_publication'),
    path('gallery/', views.gallery, name='gallery'),
    path('teacher_list/', views.teacher_list, name='teacher_list'),
    path('teacher_details/<int:pk>/', views.teacher_details, name='teacher_details'),
    path('facilites/<int:pk>/', views.facilites, name='facilites'),
    path('seminar_library/', views.seminar_Library, name='seminar_Library'),
    path('computer_lab/', views.computer_lab, name='computer_lab'),
    path('crime_lab/', views.crime_lab, name='crime_lab'),
    path('bss_syllabus/', views.bss, name='bss'),
    path('mss_syllabus/', views.mss, name='mss_syllabus'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('mphil/',views.mphil_phd,name='mphil'),

    # path('past_event_details/<int:pk>/',views.pastevent_details,name='past_event_details'),

]

Criminology_App/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Home(models.Model):
    slider_one = models.ImageField(upload_to='profile_pics')
    slider_two = models.ImageField(upload_to='profile_pics')
    slider_three = models.ImageField(upload_to='profile_pics')

    class Meta:
        ordering = ['-slider_one', ]


class ChairmanMessage(models.Model):
    departmnent_intro = models.TextField(max_length=4000, verbose_name='Put here department introduction')
    chairman_name = models.TextField(max_length=120, verbose_name='write here chariman Name')
    chairman_role = models.TextField(max_length=300, verbose_name='write hete chairman Role detials',blank=True)
    chairman_img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.chairman_name


class Facilite(models.Model):
    facilites_title = models.TextField(max_length=700, verbose_name='Put your facilites title here')
    facilites_img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.facilites_title


class Facilites_details(models.Model):
    title = models.ForeignKey(Facilite, on_delete=models.CASCADE)
    details = models.TextField(max_length=30000, verbose_name='Put here facilites details')

    def __str__(self):
        return str(self.title)


class Program(models.Model):
    program_name = models.TextField(max_length=400, verbose_name='put here program Heading', blank=True)
    program_details = models.TextField(max_length=1000, verbose_name='put here program Heading', blank=True)

    def __str__(self):
        return self.program_name


class UpcomingEvents(models.Model):
    event_title = models.TextField(max_length=400, verbose_name='write here Event tile',blank=True)
    event_date = models.CharField(max_length=20, verbose_name='put here date',blank=True)
    event_details = models.TextField(max_length=1000, verbose_name='Put here event details',blank=True)
    event_img = models.ImageField(upload_to='gallery',blank=True)
    event_file = models.FileField(upload_to='event_docx',blank=True)

    def __str__(self):
        return self.event_title


class About(models.Model):
    about_image = models.ImageField(upload_to='profile_pics')
    about_details = models.TextField(max_length=10000, verbose_name='Put here About Deatils')
    mission_title = models.TextField(max_length=1000, verbose_name='write here your mission title')
    mission_details = models.TextField(max_length=10000, verbose_name='write here mission details')

    def __str__(self):
        return self.about_details


class Eventlist(models.Model):
    events_title = models.CharField(max_length=333, verbose_name='Put a Event title here')
    events_img = models.ImageField(upload_to='profile_pics')
    events_date = models.CharField(max_length=120, verbose_name='Put here static date')

    def __str__(self):
        return self.events_title


class Event_Detail(models.Model):
    event_title = models.ForeignKey(Eventlist, on_delete=models.CASCADE)
    events_details = models.TextField(max_length=300000, verbose_name='Put a event details here')

    def __str__(self):
        return str(self.event_title)


class TeacherList(models.Model):
    teacher_name = models.CharField(max_length=212, verbose_name='Put a teacher name')
    teacher_img = models.ImageField(upload_to='profile_pics')
    teacher_designation = models.TextField(max_length=400, verbose_name='Put a teacher designation here')
    teacher_fb = models.URLField(max_length=200, verbose_name='Put here teacher Facebook id link')
    teacher_twitter = models.URLField(max_length=200, verbose_name='Put here teacher twitter id link')
    teacher_linkldn = models.URLField(max_length=200, verbose_name='Put here teacher Linkldn id link')

    def __str__(self):
        return self.teacher_name


class Teacher_Detail(models.Model):
    teacher_name = models.ForeignKey(TeacherList, on_delete=models.CASCADE)
    teacher_subjetct = models.TextField(max_length=600, verbose_name='Put which subject are you taken')
    research_interest = models.TextField(max_length=700, verbose_name='put here your reaserach and interest')
    teacher_cv = models.FileField(upload_to='Cv', blank=False)

    def __str__(self):
        return str(self.teacher_name)


class Research_Publication(models.Model):
    research_title = models.TextField(max_length=1000, verbose_name='Write here research title', blank=True)
    research_details = models.TextField(max_length=10000, verbose_name='Write here research details', blank=True)

    def __str__(self):
        return self.research_title


class Gallery(models.Model):
    img_one = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_two = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_three = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_four = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_five = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_six = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_seven = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)
    img_eight = models.ImageField(upload_to='gallery', verbose_name='Drop a Image', blank=False)

    def __str__(self):
        return str(self.img_one)


class Seminar_Lab(models.Model):
    seminar_image = models.ImageField(upload_to='gallery', verbose_name='image size should be', blank=False)
    seminar_details = models.TextField(max_length=10000, verbose_name='write here seminar details')

    def __str__(self):
        return self.seminar_details


class Computer_Lab(models.Model):
    lab_image = models.ImageField(upload_to='gallery', verbose_name='image size should be', blank=False)
    lab_details = models.TextField(max_length=10000, verbose_name='write here seminar details')

    def __str__(self):
        return self.lab_details


class Crime_Lab(models.Model):
    lab_image = models.ImageField(upload_to='gallery', verbose_name='image size should be', blank=False)
    lab_details = models.TextField(max_length=10000, verbose_name='write here seminar details')

    def __str__(self):
        return self.lab_details


class Bss_syllabus(models.Model):
    syllabus_file = models.FileField(upload_to='syllabus', verbose_name='Upload here any file')

    def __str__(self):
        return str(self.syllabus_file)


class Mss_syllabus(models.Model):
    syllabus_file = models.FileField(upload_to='syllabus', verbose_name='Upload here any file')

    def __str__(self):
        return str(self.syllabus_file)


class Mphil_phd(models.Model):
    syllabus_file = models.FileField(upload_to='syllabus', verbose_name='Upload here any file')

    def __str__(self):
        return str(self.syllabus_file)


class HeaderAndFooter(models.Model):
    phone_number = models.CharField(max_length=100)
    facebook_link = models.URLField(max_length=100, verbose_name='Facebook Link')
    twitter_link = models.URLField(max_length=100, verbose_name='Twitter Link')
    google_link = models.URLField(max_length=100, verbose_name='Google Plus Link')
    linkedin_link = models.URLField(max_length=100, verbose_name='LinkedIn Link')
    instagram_link = models.URLField(max_length=100, verbose_name='Instagram Link')

    def __str__(self):
        return str(self.id)




class SecondEvent(models.Model):
    event_title=models.CharField(max_length=440)
    event_file=models.FileField(upload_to='Publication')

    def __str__(self):
        return self.event_title

Criminology_App/forms.py
from django import forms



class ContactForm(forms.Form):
    email = forms.EmailField()

Criminology_App/views.py
import os.path
from django.db import models
from django.shortcuts import render, HttpResponse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.contrib import messages
from Criminology_App.forms import ContactForm
from django.core.mail import send_mail, EmailMessage
from django.contrib.auth.models import User
from django.views.generic.edit import DeleteView
from django.views import View
# from Criminology_App.models import (Home, About, Eventlist, Teacher_Detail,
#                                     TeacherList,
#                                     Gallery, Event_Detail, UpcomingEvents, Program,
#                                     ChairmanMessage, Facilite, Facilites_details,
#                                     Research_Publication, Seminar_Lab, Computer_Lab, Crime_Lab, Bss_syllabus,
#                                     Mss_syllabus, Mphil_phd, Event_Detail)

from Criminology_App.models import *


# Create your views here.

def index(request):
    home = Home.objects.all()
    fc = Facilite.objects.all()
    up_events = UpcomingEvents.objects.all()
    program = Program.objects.all()
    second=SecondEvent.objects.all()
    welcome = ChairmanMessage.objects.all()

    dict = {'home': home, 'up_events': up_events, 'program': program,
            'welcome': welcome, 'fc': fc,'second':second}
    return render(request, 'Criminology_App/index.html', context=dict)


def facilites(request, pk):
    exp = Facilites_details.objects.get(title_id=pk)
    expp = Facilite.objects.get(id=pk)
    dict = {'exp': exp, 'expp': expp}
    return render(request, 'Criminology_App/feature_details.html', context=dict)


def about(request):
    about = About.objects.all()
    dict = {'about': about}
    return render(request, 'Criminology_App/about.html', context=dict)


# =============Send mail
class Contact(TemplateView):
    template_name = './Criminology_App/contact.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        message = "From: " + email + "/n"  " " + message

        mail = EmailMessage(subject, message, to=[settings.EMAIL_HOST_USER])
        mail.content_subtype = 'html'
        mail.send()
        return render(request, './Criminology_App/contact.html', context={})


# ==========Send mail


def research_publication(request):
    rp = Research_Publication.objects.all()

    dict = {'rp': rp}
    return render(request, 'Criminology_App/ResearchPublication.html', context=dict)


def gallery(request):
    img = Gallery.objects.all
    dict = {'img': img}
    return render(request, 'Criminology_App/gallery.html', context=dict)


def events(request):
    events_list = Eventlist.objects.all()
    dict = {'events_list': events_list}
    return render(request, 'Criminology_App/events.html', context=dict)


def event_details(request, pk):
    event_info = Event_Detail.objects.get(event_title_id=pk)
    single_event = Eventlist.objects.get(id=pk)
    dict = {'event_info': event_info, 'single_event': single_event}
    return render(request, 'Criminology_App/event-details.html', context=dict)


def teacher_list(request):
    teacher_list = TeacherList.objects.all().order_by('id')
    dict = {'teacher_list': teacher_list}
    print('test', dict)
    return render(request, 'Criminology_App/faculty.html', context=dict)


def teacher_details(requests, pk):
    teacher_details = Teacher_Detail.objects.get(teacher_name_id=pk)
    teacher_data = TeacherList.objects.get(id=pk)
    print(teacher_details)
    dict = {'teacher_details': teacher_details, 'teacher_data': teacher_data}

    return render(requests, 'Criminology_App/card_details.html', context=dict)


def seminar_Library(request):
    smlab = Seminar_Lab.objects.all()
    dict = {'smlab': smlab}

    return render(request, 'Criminology_App/SeminarLibrary.html', context=dict)


def computer_lab(request):
    comp = Computer_Lab.objects.all()
    dict = {'comp': comp}

    return render(request, 'Criminology_App/Computer_Lab.html', context=dict)


def crime_lab(request):
    crm_lab = Crime_Lab.objects.all()
    dict = {'crm_lab': crm_lab}

    return render(request, 'Criminology_App/Crime_Lab.html', context=dict)


def bss(request):
    bs_syllabus = Bss_syllabus.objects.all()
    dict = {'bs_syllabus': bs_syllabus}

    return render(request, 'Criminology_App/B.S.S.html', context=dict)


def mss(request):
    mss_syllabus = Mss_syllabus.objects.all()
    dict = {'mss_syllabus': mss_syllabus}

    return render(request, 'Criminology_App/M.S.S.html', context=dict)


def mphil_phd(request):
    m_phd = Mphil_phd.objects.all()
    dict = {'m_phd': m_phd}

    return render(request, 'Criminology_App/Mphil_phd.html', context=dict)

templates/Criminology_App/B.S.S.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock %}

{% block body_block %}

     <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        B.S.S. Syllabus
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

<section class="syllabus_bss">
        <div class="container mt-5 mb-5">
            {% for x in bs_syllabus %}
            <div class="row">
                <div class="col-md-12">
                    <p> B.S.S. Updated Syllabus <a target="_blank" href="{{ x.syllabus_file.url }}">
                            <button
                                    class="btn btn-info btn-sm">download
                            </button>
                        </a>

                        </p>
                </div>
            </div>
            {% endfor %}
        </div>
</section>


{% endblock %}

templates/Criminology_App/Computer_Lab.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock %}

{% block body_block %}

    <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        Computer Lab
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->


    <!-- Start info Area -->
    <section class="info-area pb-120">
        <div class="container-fluid">
               {% for x in comp %}
            <div class="row align-items-center">
                <div class="col-lg-6 no-padding info-area-left">
                    <img class="img-fluid" src="{{ x.lab_image.url}}" alt="">
                </div>
                <div class="col-lg-6 info-area-right">
                    <h1>Computer Lab</h1>
                    <p>{{ x.lab_details|safe }}</p>


                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- End info Area -->

    <!-- Start course-mission Area -->


{% endblock %}

templates/Criminology_App/M.S.S.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}{{ Home }}{% endblock %}

{% block body_block %}

     <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        M.S.S. Syllabus
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

<section class="syllabus_bss">
        <div class="container mt-5 mb-5">
            {% for x in mss_syllabus %}
            <div class="row">
                <div class="col-md-12">
                    <p> Updated Syllabus M.S.S. <a target="_blank" href="{{ x.syllabus_file.url }}">
                            <button
                                    class="btn btn-info btn-sm">download
                            </button>
                        </a>.
                        </p>
                </div>
            </div>
            {% endfor %}
        </div>
</section>


{% endblock %}

templates/Criminology_App/Mphil_phd.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}{{ Home }}{% endblock %}

{% block body_block %}

     <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                     MPhil. and Ph.D.
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

<section class="syllabus_bss">
        <div class="container mt-5 mb-5">
            {% for x in m_phd %}
            <div class="row">
                <div class="col-md-12">
                    <p>M.Phil & Ph.D. Admission Rules  <a target="_blank" href="{{ x.syllabus_file.url }}">                            <button
                                    class="btn btn-info btn-sm">download
                            </button>
                        </a>
                        </p>
                </div>
            </div>
            {% endfor %}
        </div>
</section>


{% endblock %}

templates/Criminology_App/SeminarLibrary.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock %}

{% block body_block %}

    <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                       Seminar Library
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->


    <!-- Start info Area -->
    <section class="info-area pb-120">
        <div class="container-fluid">
                {% for x in smlab %}
            <div class="row align-items-center">
                <div class="col-lg-6 no-padding info-area-left">
                    <img class="img-fluid" src="{{ x.seminar_image.url }}" alt="">
                </div>
                <div class="col-lg-6 info-area-right">
                    <h1>Seminar Library</h1>
                    <p>{{ x.seminar_details|safe }}</p>


                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- End info Area -->

    <!-- Start course-mission Area -->


{% endblock %}

templates/Criminology_App/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}{{ Home }}{% endblock %}

{% block body_block %}



    <!-- start banner Area -->
    <section class="banner-area relative about-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        Contact Us
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'Criminology_App:contact' %}"> Contact Us</a></p>
                </div>
            </div>
        </div>
    </section>

{#  =============== end banner area =================#}

    <div class="location">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3652.3742131317017!2d90.39075291434816!3d23.734031395319754!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8c1ef1cf437%3A0xa268523b59dae27b!2sDepartment%20of%20Criminology!5e0!3m2!1sen!2sbd!4v1625157009223!5m2!1sen!2sbd" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>

    <!-- Start contact-page Area -->
			<section class="contact-page-area section-gap">
				<div class="container">
					<div class="row">

						<div class="col-lg-4 d-flex flex-column address-wrap">

							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-home"></span>
								</div>
								<div class="contact-details">
									<h5>University of Dhaka</h5>
									<p>
										Bangaladesh Dhaka
									</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-phone-handset"></span>
								</div>
								<div class="contact-details">
									<h5>+880 1714-531265</h5>
									<p>Mon to Fri 9am to 6 pm</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-envelope"></span>
								</div>
								<div class="contact-details">
									<h5>criminology@du.ac.bd</h5>
									<p>Send us your query anytime!</p>
								</div>
							</div>
						</div>
                        <hr>
						<div class="col-lg-8">
                              <div class="contact-form">
                        <div id="success"></div>

                         <form  action="{% url 'Criminology_App:contact' %}" method="POST" name="sentMessage" id="contactForm" novalidate="novalidate">
                             {% csrf_token %}

                            <div class="control-group">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                <p class="help-block"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                <p class="help-block"></p>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control " id="message" name="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message">{{message}}</textarea>

                                <p class="help-block"></p>
                            </div>

                            <div>

                                <button class="btn btn-info" type="submit" id="sendMessageButton">Send Message</button>

                            </div>

                        </form>

                    </div>
                        </div>
			</section>
			<!-- End contact-page Area -->

{% endblock %}

templates/Criminology_App/events.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}{{ Home }}{% endblock %}

{% block body_block %}


<!-- start banner Area -->
<section class="banner-area relative about-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Our Notice
                </h1>
                <p class="text-white link-nav"><a href="{% url 'Criminology_App:index' %}">Home </a> <span
                        class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'Criminology_App:event' %}"> Events</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->




<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
    <h3 class="text-center">Our Notice</h3>
    <div class="container">
        <div class="row align-items-center">

            {% for x in events_list %}
                <div class="col-lg-6 pb-30">

                    <div class="single-carusel row align-items-center">
                        <div class="col-12 col-md-6 thumb">
                            <img class="img-fluid" src="/media/{{ x.events_img }}" alt="">
                        </div>
                        <div class="detials col-12 col-md-6">
                            <p>{{ x.events_date|safe }}</p>
                            <a href="{% url 'Criminology_App:event_details' pk=x.id %}">
                                <h4>{{ x.events_title|safe }}</h4></a>
                            <p>
                                {{ x.events_details|safe }}
                            </p>
                        </div>
                    </div>

                </div>
            {% endfor %}



        </div>
    </div>
</section>
<!-- End events-list Area -->




{% endblock %}

templates/Criminology_App/faculty.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}{{ Home }}{% endblock %}

{% block body_block %}


    <!-- start banner Area -->
    <section class="banner-area relative blog-home-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content blog-header-content col-lg-12">
                    <h1 class="text-white">
                        Faculty
                    </h1>
                    <h3 class="tch">Profile</h3>

                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->


    <!--========================Teacher section start==============-->

    <section id="teacher">
        <div class="container">
            <div class="row">
                {% for x in teacher_list %}
                    <div class="col-md-4">

                        <div class="team-body shadow mx-5 my-5 text-center">

                            <div class="team-avatar"><a href="{% url 'Criminology_App:teacher_list' %}"><img
                                    src="/media/{{ x.teacher_img  }}" class="img-thumbnail" alt=""></a></div>
                            <div class=" team-name mt-4">
                                <a href="{% url 'Criminology_App:teacher_details' pk=x.id %}">
                                    <h4>{{ x.teacher_name|safe }}</h4>
                                </a>
                            </div>
                            <div class="team-designation"><p>{{ x.teacher_designation|safe }}</p></div>
                            <div class="team-social-links d-flex flex-row justify-content-center">
                                <a href="{{ x.teacher_fb }}" id="fb"><i class="fab fa-facebook-f"></i></a>
                                <a href="{{ x.teacher_twitter }}" id="twitter"><i class="fab fa-twitter"></i></a>
                                <a href="{{ x.teacher_linkldn }}" id="linkedin"><i class="fab fa-linkedin"></i></a>
                            </div>

                        </div>


                    </div>
                {% endfor %}

            </div>
        </div>
    </section>


    <!--=====================Teacher's Section End================-->


{% endblock %}